### ISSUE TITLE
Search input text color

### ISSUE THREAD

**Issue by MikeNGarrett** [codeforrva/food-access-finder#22]
Search input text color is light for the weight of the font. On mobile devices and Windows-based machines it appears illegible. 
![screen shot 2016-08-10 at 8 34 25 pm](https://cloud.githubusercontent.com/assets/394888/17575762/2e2f9d7e-5f3a-11e6-98a0-029a778e5bde.png)

**Comment by shoveria** [comment]
got it 👍 

bumped it up to 300
